# Generated by Django 6.0.3 on 2026-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('lgbtq_plus', 'LGBTQ+'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
