# Generated by Django 6.0.3 on 2026-04-01 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_userprofile_name_userprofile_surname'),
        ('tasks', '0004_alter_task_due_date_taskcategory_alter_task_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_download', models.ManyToManyField(blank=True, help_text='Users who can download this file', related_name='downloadable_files', to=settings.AUTH_USER_MODEL)),
                ('can_edit', models.ManyToManyField(blank=True, help_text='Users who can edit this file', related_name='editable_files', to=settings.AUTH_USER_MODEL)),
                ('can_view', models.ManyToManyField(blank=True, help_text='Users who can view this file', related_name='viewable_files', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.comment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='projects_fi_project_2c056b_idx'), models.Index(fields=['task', 'created_at'], name='projects_fi_task_id_f3e7bc_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='projects_fi_uploade_91a559_idx')],
            },
        ),
    ]
