# Generated by Django 6.0.3 on 2026-04-24 14:22

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_fileattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(upload_to=projects.models.attachment_upload_path),
        ),
    ]
