# Generated by Django 6.0.3 on 2026-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='credit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='หน่วยกิต (0-9)', null=True),
        ),
    ]
