# Generated by Django 6.0.3 on 2026-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_scheduleentry_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='section',
            field=models.CharField(blank=True, default='', help_text='เซ็คชั่น เช่น 001, 002', max_length=20),
        ),
    ]
