# Generated by Django 6.0.3 on 2026-04-07 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_scheduleentry_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, default='')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(choices=[('indigo', 'สีม่วงน้ำเงิน'), ('green', 'สีเขียว'), ('rose', 'สีชมพู'), ('amber', 'สีเหลือง'), ('sky', 'สีฟ้า'), ('orange', 'สีส้ม')], default='indigo', max_length=10)),
                ('remind_before', models.PositiveSmallIntegerField(default=15, help_text='แจ้งเตือนก่อน (นาที): 0=ไม่แจ้ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
