# Generated by Django 6.0.3 on 2026-04-07 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='schedules.schedule'),
        ),
    ]
